---
inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'public/**/*'
    - 'test/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

Style/GlobalVars:
  AllowedVariables:
    - $redis

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 250

Metrics/AbcSize:
  Max: 35

Metrics/MethodLength:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

RSpec/VariableName:
  EnforcedStyle: snake_case
  AllowedPatterns:
    - ^Authorization

Style/HashSyntax:
  EnforcedShorthandSyntax: never

RSpec/ImplicitExpect:
  EnforcedStyle: should

ImplicitSubject:
  EnforcedStyle: require_implicit

Rails/WhereNotWithMultipleConditions:
  Enabled: false

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false
