version: '3.4'

x-backend-app: &backend-app
  build:
    context: .
    dockerfile: Dockerfile.dev
  restart: on-failure
  environment:
    RAILS_ENV: development
    NODE_ENV: development
    REDIS_URL: redis://redis:6379
    EDITOR: vim
  stdin_open: true
  tty: true
  volumes:
    - .:/home/www/rails-app:rw
    - /home/www/rails-app/tmp/cache/bootsnap
    - /home/www/rails-app/vendor/bundle
    - /home/www/rails-app/storage

services:
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data

  redis:
    image: redis:6.2.1-alpine
    command: redis-server
    ports:
      - 6379:6379/tcp
    volumes:
      - ../data/redis:/data

  sidekiq:
    <<: *backend-app
    command: bundle exec sidekiq
    depends_on:
      - backend
      - redis

  backend:
    <<: *backend-app
    entrypoint: ./docker-entrypoint.sh
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - 3000:3000/tcp
    depends_on:
      - postgres
      - redis
