default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials[:db_username] || 'postgres' %>
  password: <%= Rails.application.credentials[:db_password] || 'postgres' %>
  host: <%= Rails.application.credentials[:db_host] || 'postgres' %>
  port: <%= Rails.application.credentials[:db_port] || 5432 %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'api' } %>_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'api' } %>_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

staging:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'api' } %>_staging
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'api' } %>_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 40 } %>
